estimator:
  pickle: model.pickle

strategy:
  name: random


search_space:
  hidden_neurons_1:
    min: 10
    max: 400
    type: int

  hidden_neurons_2:
    min: 5
    max: 200
    type: int

  batch_size:
    min: 10
    max: 50
    type: int

  epochs:
    min: 10
    max: 2000
    type: int

  learning_rate:
    min: 2.5e-4
    max: 3e-3
    type: float
    warp: log

  l2:
    min: 1e-8
    max: 3e-4
    type: float
    warp: log

  l1:
    min: 1e-8
    max: 1e-4
    type: float
    warp: log

cv:
  name: kfold
  params:
    n_splits: 3

dataset_loader:
  name: joblib
  params:
    filenames: activity.pickle
    x_name: X
    y_name: y

trials:
    uri: sqlite:///activity.db

